// Generated by CoffeeScript 2.5.1
import m from 'mithril';

import {
  Icon,
  Button
} from "polythene-mithril";

import "polythene-css";

import {
  defaultsDeep
} from 'lodash';

export var DefaultButton = {
  view: function({attrs}) {
    return m(Button, defaultsDeep(attrs, {
      border: true
    }));
  }
};

export var PrimaryButton = {
  view: function({attrs}) {
    return m(DefaultButton, defaultsDeep(attrs, {
      rised: true
    }));
  }
};

// element: "button"
export var saveButton = {
  view: function({attrs}) {
    return m(PrimaryButton, {
      label: '保存'
    });
  }
};
