// Generated by CoffeeScript 2.5.1
import m from 'mithril';

import {
  Icon,
  TextField
} from "polythene-mithril";

import "polythene-css";

import {
  defaultsDeep
} from 'lodash';

// import userIcon from '../zondicons/user.svg'
export var Input = {
  view: function({attrs}) {
    return m(TextField, defaultsDeep(attrs, {
      floatingLabel: true
    }));
  }
};

// fullWidth: true
// todo 增加图标支持
// before: m Icon,{svg:content:userIcon}
export var AccountInput = {
  view: function({attrs}) {
    return m(Input, defaultsDeep(attrs, {
      label: '账号',
      required: true,
      error: '请输入账号'
    }));
  }
};

export var MobileInput = {
  view: function({attrs}) {
    return m(Input, defaultsDeep(attrs, {
      label: '手机号',
      required: true,
      error: '请输入手机号',
      maxlength: 11,
      minlength: 11,
      pattern: /^1[0-9](10)$/
    }));
  }
};

export var PasswordInput = {
  view: function({attrs}) {
    return m(Input, defaultsDeep(attrs, {
      label: '密码',
      required: true,
      type: 'password',
      error: '请输入密码'
    }));
  }
};
