// Generated by CoffeeScript 2.5.1
import m from 'mithril';

import {
  Toolbar,
  ToolbarTitle,
  Tabs,
  IconButton,
  Button,
  Menu,
  List,
  ListTile
} from "polythene-mithril";

import {
  addLayoutStyles
} from "polythene-css";

import {
  defaultsDeep
} from 'lodash';

addLayoutStyles();

import {
  MDIcon,
  mdiAccount
} from '../component/MDIcon';
import { UserBar } from './UserBar';

export var AdminLayout = {
  oninit: function ({ attrs, state }) {
    state.show = false;
    state.defaultNav = {
      tabs: []
    };
    state.safeUser = {
      id: 'mm_user_button',
      icon: {
        svg: {
          content: m(MDIcon, mdiAccount)
        }
      },
      dropdown: {
        show: state.show
      },
      events: {
        onclick: (e) => {
          state.show = !state.show;
        }
      }
    };
    state.defaultUserMenu = {
      tiles: []
    };
    state.safeMenu = {
      target: '#mm_user_button',
      origin: 'top right',
      offsetV: '80px',
      // show: state.show,
      show: true,
      didHide: function () {
        state.show = false;
      },
    };
    state.defaultMain = {
      style: {
        'background-color': '#eee'
      }
    }
  },
  view: function ({ attrs, state, children }) {
    console.log(attrs.userMenu);
    return m('.admin.layout.vertical.pe-fullbleed', [
      m(Toolbar, [
        m(ToolbarTitle, attrs.title),
        m(Tabs, defaultsDeep(
          attrs.nav,
          state.defaultNav,
        )),
        m(UserBar, attrs.userBar),
        // m(Button, defaultsDeep(
        //   state.safeUser,
        //   attrs.user,
        // )),
        // m(Menu, defaultsDeep(
        //   state.safeMenu,
        //   {
        //     content: m(List, attrs.userMenu)
        //   }

        //   // m(List, defaultsDeep(
        //   //   attrs.userMenu,
        //   //   state.defaultUserMenu
        //   // ))
        // ))
      ]),
      m('.main.flex.one', defaultsDeep(
        attrs.main,
        state.defaultMain
      ), children)
    ]);
  }
};
