// Generated by CoffeeScript 2.5.1
var iconMenuSVG;

import m from 'mithril';

import {
  Toolbar,
  IconButton,
  Drawer,
  List,
  ListTile,
  Icon
} from "polythene-mithril";

import "polythene-css";

iconMenuSVG = '<svg width="24" height="24" viewBox="0 0 24 24"> <path d="M3 18h18v-2H3v2zm0-5h18v-2H3v2zm0-7v2h18V6H3z"/> </svg>';

export var ddDrawer = {
  oninit: function({state, attrs}) {
    state.showDrawer = false;
    return state.navList = attrs.navList || [];
  },
  view: function({state, attrs, children}) {
    return m('.warp', {}, [
      m(Toolbar,
      {
        border: true
      },
      [
        m(IconButton,
        {
          icon: {
            svg: {
              content: m.trust(iconMenuSVG)
            }
          },
          events: {
            onclick: function() {
              return state.showDrawer = !state.showDrawer;
            }
          }
        }),
        m("div",
        {
          className: "pe-toolbar__title"
        },
        attrs.title),
        attrs.right ? m('.right',
        'uc') : void 0
      ]),
      m('',
      {
        style: {
          position: "relative"
        }
      },
      [
        // overflow: "hidden"
        m('.drawer-warp',
        {
          style: {
            display: "flex",
            height: "100%",
            background: "#fff"
          }
        },
        [
          // color: "#333"
          m(Drawer,
          {
            push: true,
            border: true,
            mini: true,
            className: "small-screen-cover-drawer medium-screen-mini-drawer large-screen-floating-drawer",
            show: state.showDrawer,
            content: m(List,
          {
              tiles: state.navList.map(function({title,
          icon}) {
                return m(ListTile,
          {
                  title: title,
                  front: m(Icon,
          {
                    svg: {
                      content: m.trust(icon)
                    }
                  }),
                  hoverable: true,
                  navigation: true
                });
              })
            }),
            // events: {
            //   onclick: navItemClick
            // }
            //   navigationList({
            //   handleClick: () -> state.showDrawer = false
            // }),
            didHide: function() {
              return state.showDrawer = false;
            }
          }),
          m(".content",
          {
            style: {
              overflow: "hidden",
              flexShrink: 0,
              flexGrow: 0,
              width: "100%"
            }
          },
          children)
        ])
      ])
    ]);
  }
};
