// Generated by CoffeeScript 2.5.1
import m from 'mithril';

// {Nav,Brand,Menu,Footer} = require '..//index'
export var SimpleLayout = {
  init: function({attrs}) {},
  // attrs.brand ?= '111'
  view: function({attrs, children}) {
    console.log(111111111111);
    console.log(attrs);
    console.log(children);
    return m('.simple', {
      id: attrs.pageId
    }, [
      m('header',
      {
        class: 'navbar-fixed'
      },
      m(Nav,
      {
        class: attrs.class
      },
      [
        m(Brand,
        {},
        attrs.brand),
        m(Menu,
        {
          class: 'menu'
        },
        attrs.menuItems)
      ])),
      m('main',
      {},
      children),
      m(Footer,
      {
        copyright: attrs.copyright
      },
      attrs.footer)
    ]);
  }
};
