// Generated by CoffeeScript 2.5.1
var pull,
  indexOf = [].indexOf;

import m from 'mithril';

import {
  CheckBox
} from '../index';

({pull} = require('lodash'));

// import debug from 'debug'
// see = debug('mmui').extend 'checkBoxGroup'
export var CheckBoxGroup = class CheckBoxGroup {
  view({attrs, children}) {
    var ref;
    if (attrs.value == null) {
      attrs.value = [];
    }
    return m('.input-field', {
      class: (ref = attrs.class) != null ? ref : 'col s12'
    }, [
      children.map(function(opt) {
        var ref1,
      ref2,
      text,
      value;
        value = (ref1 = opt.value) != null ? ref1 : opt;
        text = (ref2 = opt.text) != null ? ref2 : value;
        return m(CheckBox,
      {
          value: value,
          checked: indexOf.call(attrs.value,
      value) >= 0,
          onchange: function({target}) {
            if (target.checked) {
              return attrs.value.push(target.value);
            } else {
              return pull(attrs.value,
      target.value);
            }
          }
        },
      text);
      }),
      m('label',
      attrs.label)
    ]);
  }

};
