// Generated by CoffeeScript 2.5.1
import m from 'mithril';

module.exports = class {
  view({attrs, children}) {
    return m('footer.page-footer', [m('.container', children), m('.footer-copyright', m('.container', m(attrs.copyright)))]);
  }

};
