// Generated by CoffeeScript 2.5.1
//svg icon
import m from 'mithril';

import {
  defaultsDeep
} from 'lodash';

export * from '@mdi/js';

export var MDIcon = {
  view: function({attrs, children}) {
    defaultsDeep(attrs, {});
    if (typeof children === 'string') {
      children = [children];
    }
    return m('svg', attrs, children.map(function(child) {
      return m('path', {
        d: child
      });
    }));
  }
};
