// Generated by CoffeeScript 2.5.1
import m from 'mithril';

module.exports = class {
  view(vnode) {
    return m('.metric', [m('.title', vnode.attrs.title), m('.value', vnode.attrs.value)]);
  }

};
